version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /mywebapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /mywebapp/docker-credentials/token  # Updated to use the PAT
    DOCKER_REGISTRY_URL: /mywebapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r day-14/simple-python-app/requirements.txt
      # Check if token is not empty
      - if [ -z "$DOCKER_REGISTRY_PASSWORD" ]; then echo "DOCKER_REGISTRY_PASSWORD (token) is empty"; exit 1; fi
      # Login to Docker registry using PAT
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
  build:
    commands:
      - cd day-14/simple-python-app
      - echo "Building Docker Image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest" .
      - if [ $? -ne 0 ]; then echo "Docker build failed"; exit 125; fi
      - echo "Pushing Docker Image"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"
      - if [ $? -ne 0 ]; then echo "Docker push failed"; exit 125; fi
 post_build:
    commands:
      - echo "Build is Successful"

artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app

