version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /mywebapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /mywebapp/docker-credentials/token
    DOCKER_REGISTRY_URL: /mywebapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r day-14/simple-python-app/requirements.txt
      - if [ -z "$DOCKER_REGISTRY_PASSWORD" ]; then echo "DOCKER_REGISTRY_PASSWORD (token) is empty"; exit 1; fi
      # Login to Docker registry using PAT
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
  build:
    commands:
      - echo "Running tests..."
      - cd day-14/simple-python-app/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
      - docker push "docker.io/arpita199812/simple-python-flask-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'        # Include all files and directories in the build output
  base-directory: './day-14/simple-python-app' 
  name: 'code_artifact'
